# Generated by Django 4.1.7 on 2023-04-25 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("RP_Agg", "0002_paper_remove_userpaperpreference_preferences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
