# Generated by Django 4.1.7 on 2023-04-25 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("RP_Agg", "0003_paper_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="user",
        ),
        migrations.AddField(
            model_name="paper",
            name="users",
            field=models.ManyToManyField(
                related_name="papers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
